- docs/user/custom_resource.md
- docs/user/tls.md
- examples/simple-cluster-no-tls.yaml
- examples/simple-cluster-tls.yaml
- pkg/apis/deployment/v1alpha/deployment_spec.go
- pkg/apis/deployment/v1alpha/tls_spec.go
- pkg/apis/deployment/v1alpha/tls_spec_test.go
- pkg/deployment/pod_creator_agent_args_test.go
- pkg/deployment/pod_creator_coordinator_args_test.go
- pkg/deployment/pod_creator_dbserver_args_test.go
- pkg/deployment/pod_creator_single_args_test.go
- pkg/util/arangod/client.go
Change default behavior of TLS from off to on.
> Turn on TLS by default

- pkg/operator/operator_deployment.go
It failed because the validation was done to soon, which in resulted in the reset logic being skipped.
Now the early validation is only done for completely new deployments.
For existing deployments, the validation is done in the `deployment` package.
> Fixed immitable `mode` field.

- Makefile
- pkg/deployment/deployment.go
- pkg/deployment/deployment_inspector.go
- pkg/deployment/pod_inspector.go
- pkg/deployment/reconcile/action.go
- pkg/deployment/reconcile/action_add_member.go
- pkg/deployment/reconcile/action_cleanout_member.go
- pkg/deployment/reconcile/action_context.go
- pkg/deployment/reconcile/action_remove_member.go
- pkg/deployment/reconcile/action_rotate_member.go
- pkg/deployment/reconcile/action_shutdown_member.go
- pkg/deployment/reconcile/action_upgrade_member.go
- pkg/deployment/reconcile/action_wait_for_member_up.go
- pkg/deployment/reconcile/errors.go
- pkg/deployment/reconcile/plan_builder.go
- pkg/deployment/reconcile/plan_builder_test.go
- pkg/deployment/reconcile/plan_executor.go
- pkg/deployment/reconcile/reconcile_context.go
- pkg/deployment/reconcile/reconciler.go
- pkg/deployment/reconcile_context_impl.go
Done to improve separation in the code.
High level reconciliation logic is now in its own package.
> Moved reconciliation code to separate package

- pkg/deployment/context_impl.go
- pkg/deployment/deployment_inspector.go
- pkg/deployment/resources/context.go
- pkg/deployment/resources/pod_cleanup.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/resources/pod_inspector.go
- tests/resilience_test.go
Pods normally have a period between termination and cleanup by the kubernetes pod garbage collection.
This PR adds our own cleanup, to make the time between pod termination and pod being gone as short as possible.
> Added terminated-pod cleanup to speed up re-creation of pods.

- pkg/deployment/reconcile/plan_executor.go
Avoid overwriting Status updating the plan which is being executed.
This did happen and as a result, members being added by the scale-up (addmember)
action where never added because this change was overwritten immediately.
> Fix scale-up

- Jenkinsfile.groovy
With this PR you can control jenkins parameters using git commit messages.
Examples:
- Put `[ci LONG=1]` in your commit log and it will run long tests.
- Put `[ci TESTOPTIONS="-test.run ^TestImmutableStorageEngine$"]` in your commit logs and in will run the selected test only.
You can put many `[ci ...]` blocks in your commit log. Recent blocks overwrite older ones.
> Control jenkins from git commit log.

- pkg/apis/deployment/v1alpha/deployment.go
- pkg/apis/storage/v1alpha/local_storage.go
This was incorrect anyway.
Fixing it makes the pods show up properly in the k8s dashboard.
> AsOwner no longer things the owner refers to a controller. It refers to the ArangoDeployment

- Jenkinsfile.groovy
This PR is a dirty hack to always set `LONG=true` on the jenkins `kube-arangodb-long` test.
> Enable LONG on kube-arangodb-long test

- pkg/apis/deployment/v1alpha/member_status.go
- pkg/apis/deployment/v1alpha/member_status_test.go
- pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
- pkg/deployment/reconcile/action_rotate_member.go
- pkg/deployment/reconcile/action_upgrade_member.go
- pkg/deployment/resources/pod_inspector.go
This PR records termination timestamps of the pod for each member.
Right now this information is not yet used. A future PR will perform high level operations on it, like killing a member when there are frequent terminations.
> Tracking recent pod terminations

- pkg/storage/pv_cleanup.go
- pkg/storage/pv_inspector.go
- Prevent blocking on IsNotFound errors in delete-PV
- Adding support for cleaning PV's that are created a long time ago but still unused.
> Fixing PV cleanup

- pkg/apis/deployment/v1alpha/member_status.go
- pkg/deployment/images.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/resources/pod_inspector.go
- pkg/util/k8sutil/pods.go
This PR adds additional safety when restarting a dbserver.
It ensures that the persistent volume contains a UUID file with expected content
and an ENGINE file with expected content.
> Check contents of persisted volume when dbserver is restarting

- pkg/deployment/deployment.go
- pkg/deployment/deployment_inspector.go
- pkg/storage/local_storage.go
This avoid keeping the operator busy when the deployment is already gone.
> Quickly fail when deployment no longer exists

- .gitignore
- Jenkinsfile.groovy
- Makefile
- scripts/collect_logs.sh
This PR tweaks the jenkins pipeline such that it collects logs of both operators after the test.
> Archive log files

- pkg/deployment/deployment.go
The chaos-monkey was running in the main go-routine of the operator, so no other events for `ArangoDeployment` changes would ever arrive.
> Run chaos-monkey in go-routine to avoid blocking the operator

- docs/Manual/Deployment/Kubernetes/Metrics.md
- examples/metrics/deployment-operator-servicemonitor.yaml
- manifests/templates/deployment/deployment.yaml
- manifests/templates/storage/deployment.yaml
This PR adds an example how to expose operator metrics
to Prometheus, when that is deployed using the Prometheus-Operator
by CoreOS.
> Added examples for exposing metrics to Prometheus

- pkg/apis/deployment/v1alpha/storage_engine.go
- pkg/deployment/resources/pod_creator.go
[ci LONG=1] [ci TESTOPTIONS="-test.run ^TestMemberResilienceDBServers$"]
Problem was caused by changing the values of StorageEngine enum.
> Fixed expected value for ENGINE file in init container of dbserver.

- tests/upgrade_test.go
ResilientSingle does not yet exist in 3.2
> Remove upgrade resilient single 3.2 -> 3.3 test.

- pkg/deployment/reconcile/action_wait_for_member_up.go
Upgrading/downgrading resilient single deployments failed because it tried to use a cluster "wait until ready" test.
> Fixed down/upgrading resilient single deployments.

- examples/single-server.yaml
- pkg/deployment/resources/services.go
Reason: AWS ELB do not support clientIP stickyness.
> No stickyness for EA service of type LoadBalancer

- docs/Manual/Deployment/Kubernetes/DeploymentReplicationResource.md
Specification for DC2DC configuration resource.
This spec is implemented in #143
> Adding deployment replication spec

- manifests/templates/deployment/rbac.yaml
- pkg/apis/deployment/v1alpha/deployment.go
- pkg/deployment/images.go
This PR contains fixes needed to deploy ArangoDB on OpenShift.
Tested on `minishift v1.17.0+f974f0c`.
Note that in order to make it work, also a patched version of the ArangoDB image is needed.
A `Dockerfile` as below is known to work.
```
FROM arangodb/arangodb-preview:3.3
RUN chgrp 0 /var/lib/arangodb3 && chmod 775 /var/lib/arangodb3
RUN chgrp 0 /var/lib/arangodb3-apps && chmod 775 /var/lib/arangodb3-apps
```
These changes are patched into newly released arangodb images.
> Fixes needed to run on latest openshift.

- manifests/templates/deployment/deployment.yaml
- manifests/templates/storage/deployment.yaml
This PR adds tolerations to the deployments of the operators to make them failover quicker in case of node-failure.
The tolerations assume kubernetes 1.10. `node.alpha.kubernetes.io/unreachable` is now `node.kubernetes.io/unreachable`
See https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/ for details.
> Added no-execute tolerations on operators to failover quicker

- manifests/templates/deployment-replication/deployment-replication.yaml
- manifests/templates/deployment/deployment.yaml
- manifests/templates/storage/deployment.yaml
This PR sets the number of replicas for the all operator to 2 (from 1). This ensures that 1 replica is always standing by (waiting in leader election) and able to take over quickly when the leader is not responding.
This is faster than waiting for kubernetes to terminate a pod that becomes unresponsive.
This PR also adds tolerations that were still missing on the deployment-replication operator.
> Operator high-availability

- pkg/deployment/reconcile/plan_builder.go
This PR prevent and endless rotation of pods because it specifies an empty serviceAccountName and then finds a "different" serviceAcountName of "default".
> Fix endless rotation because of serviceAccount `default`

- docs/Manual/Deployment/Kubernetes/ServicesAndLoadBalancer.md
This PR fixes & improves the documentation related to loadbalancers & services.
> Improved Service documentation

- pkg/deployment/deployment.go
- pkg/deployment/deployment_finalizers.go
- pkg/deployment/deployment_inspector.go
- pkg/util/constants/constants.go
fixes #157 
This PR adds a finalizer on an `ArangoDeployment` and only removes that when all finalizers for owned Pods & PVCs have been removed (so they are free to be deleted).
> Added finalizer on deployment, used to remove child finalizers on delete

- scripts/kube_create_storage.sh
- tests/cursor_test.go
- tests/service_account_test.go
- tests/simple_test.go
- tests/test_util.go
> Various test improvements

- pkg/deployment/resources/services.go
- pkg/util/k8sutil/services.go
This PR removes all stickyness from Services.
The reason for that is that stickyness dos not work well with loadbalancers and we have a plan for improved cursor behavior anyway.
With this PR we need to document the proper way to do cursor calls, but that will come in a separate documentation PR.
> Remove service stickyness

- docs/Manual/Deployment/Kubernetes/Authentication.md
- docs/Manual/Deployment/Kubernetes/DriverConfiguration.md
- docs/Manual/Deployment/Kubernetes/README.md
- docs/Manual/Deployment/Kubernetes/Storage.md
- docs/Manual/Deployment/Kubernetes/Tls.md
- docs/Manual/Deployment/Kubernetes/Troubleshooting.md
- docs/Manual/Deployment/Kubernetes/Upgrading.md
- docs/Manual/Deployment/Kubernetes/Usage.md
This PR contains several improvements, fixes & extensions of the manual.
> Improving documentation

- pkg/apis/deployment/v1alpha/deployment_status_members.go
- pkg/apis/deployment/v1alpha/member_status_list_test.go
- pkg/deployment/cluster_scaling_integration.go
- pkg/deployment/context_impl.go
- pkg/deployment/deployment.go
- pkg/deployment/deployment_inspector.go
- pkg/deployment/images.go
- pkg/deployment/members.go
- pkg/deployment/reconcile/action_context.go
- pkg/deployment/reconcile/context.go
- pkg/deployment/reconcile/plan_builder.go
- pkg/deployment/reconcile/plan_executor.go
- pkg/deployment/resilience/context.go
- pkg/deployment/resilience/member_failure.go
- pkg/deployment/resources/context.go
- pkg/deployment/resources/member_cleanup.go
- pkg/deployment/resources/pod_cleanup.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/resources/pod_inspector.go
- pkg/deployment/resources/pvc_inspector.go
- pkg/deployment/resources/pvcs.go
- pkg/deployment/resources/secret_hashes.go
- pkg/deployment/resources/services.go
There were some cases where status could be overwritten, resulting in member objects being listed twice.
This PR makes modifying the status a very controlled procedure. When you fetch the status you get a last version number. When updating the status, that last version has to match the current version number.
> Avoid overwriting status changes

- pkg/apis/deployment/v1alpha/deployment_status_members.go
- pkg/apis/deployment/v1alpha/member_status_list.go
- pkg/apis/deployment/v1alpha/member_status_list_test.go
- pkg/deployment/members.go
- pkg/deployment/reconcile/action_context.go
- pkg/deployment/resilience/member_failure.go
- pkg/deployment/resources/member_cleanup.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/resources/pod_inspector.go
Functions of `MemberStatusList` that modify the list itself are dangerous when called outside the direct context of `DeploymentStatusMembers`.
This PR hides those functions and exposes them on `DeploymentStatusMembers`.
> Hide "dangerous" functions of MemberStatusList

- pkg/deployment/cleanup.go
- pkg/deployment/cluster_scaling_integration.go
- pkg/deployment/deployment_finalizers.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/resources/pod_finalizers.go
- pkg/deployment/resources/pod_inspector.go
- pkg/deployment/resources/pvc_finalizers.go
- pkg/deployment/resources/pvc_inspector.go
- pkg/replication/finalizers.go
- pkg/util/k8sutil/finalizers.go
This PR holds a collection of changes that all prevent warnings in logs that are not really something to worry about:
- The scaling cluster integration that cannot reach the cluster while it is still bootstrapping
- Removing finalizers of resources that are already gone (which is perfectly valid in that case)
- Reporting that an image ID is not yet know for all 9 pods (where 1 is sufficient)
> Avoid useless warnings in log

- deps/github.com/arangodb/go-driver/Makefile
- deps/github.com/arangodb/go-driver/cluster_impl.go
- deps/github.com/arangodb/go-driver/context.go
- deps/github.com/arangodb/go-driver/cursor_impl.go
- deps/github.com/arangodb/go-driver/test/concurrency_test.go
- deps/github.com/arangodb/go-driver/test/cursor_test.go
- deps/github.com/arangodb/go-driver/test/user_auth_test.go
- deps/github.com/arangodb/go-driver/vst/protocol/chunk.go
- deps/github.com/arangodb/go-driver/vst/protocol/connection.go
- pkg/apis/deployment/v1alpha/member_status.go
- pkg/deployment/context_impl.go
- pkg/deployment/reconcile/action.go
- pkg/deployment/reconcile/action_add_member.go
- pkg/deployment/reconcile/action_cleanout_member.go
- pkg/deployment/reconcile/action_context.go
- pkg/deployment/reconcile/action_remove_member.go
- pkg/deployment/reconcile/action_renew_tls_certificate.go
- pkg/deployment/reconcile/action_rotate_member.go
- pkg/deployment/reconcile/action_shutdown_member.go
- pkg/deployment/reconcile/action_upgrade_member.go
- pkg/deployment/reconcile/action_wait_for_member_up.go
- pkg/deployment/reconcile/context.go
- pkg/deployment/reconcile/plan_builder.go
- pkg/deployment/reconcile/plan_executor.go
- pkg/util/arangod/cleanout_server.go
- pkg/util/arangod/client.go
- pkg/util/k8sutil/events.go
This PR checks the status of ongoing cleanout server action by inspecting the right keys in the agency.
If a cleanout server job has failed, the reconciliation plan is aborted.
This PR uses https://github.com/arangodb/go-driver/pull/131
> Abort reconcilientation plan on failed cleanout server

- pkg/apis/deployment/v1alpha/deployment_status_members.go
- pkg/apis/deployment/v1alpha/member_status_list.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/resources/pod_inspector.go
- pkg/util/k8sutil/probes.go
- pkg/util/k8sutil/probes_test.go
- pkg/util/k8sutil/services.go
This PR changes the readiness tests of some pods & tweaks the services used to access the database.
- The readiness probe is now added to all single & coordinator pods (before only coordinator)
- The readiness probe is done a lot quicker and more often
- The readiness probe is done on `_admin/echo` for activefailover deployments
- The database & external access services no only accept ready endpoints
As a result, activefailover deployments only expose the master single server.
Also a cluster deployment exposes only ready coordinators.
> Improved readiness probe, database services only use ready pods

- Makefile
- pkg/storage/provisioner/mocks/mocks.go
- pkg/storage/provisioner/mocks/provisioner.go
- pkg/storage/pv_creator_test.go
Implements https://github.com/arangodb/kube-arangodb/pull/162#discussion_r193785282
> Added unit tests for pv_creator.go

- pkg/storage/pv_creator.go
This PR changes the allocation of a node in an `ArangoLocalStorage` resource.
It now tries to use distinct nodes for volumes in the same "group", even when that is not required.
If no distinct node is available AND it is not production mode, it picks one from all available nodes.
> Prefer distinct nodes, even when not required

- Makefile
- tests/duration/Dockerfile
- tests/duration/README.md
- tests/duration/main.go
- tests/duration/simple/check.go
- tests/duration/simple/error.go
- tests/duration/simple/simple.go
- tests/duration/simple/simple_collection.go
- tests/duration/simple/simple_create.go
- tests/duration/simple/simple_import.go
- tests/duration/simple/simple_query.go
- tests/duration/simple/simple_query_update.go
- tests/duration/simple/simple_read.go
- tests/duration/simple/simple_rebalance.go
- tests/duration/simple/simple_remove.go
- tests/duration/simple/simple_replace.go
- tests/duration/simple/simple_update.go
- tests/duration/test/shuffle.go
- tests/duration/test/test.go
- tests/duration/test_listener.go
- tests/duration/test_loop.go
This PR adds a simple test application that puts some load on the database to test various failure scenarios
> Added duration test app

- pkg/apis/deployment/v1alpha/server_group_spec.go
- pkg/deployment/cluster_scaling_integration.go
- pkg/deployment/reconcile/action_cleanout_member.go
- pkg/deployment/reconcile/plan_builder.go
This PR changes the following:
- Minimum server count for dbserver is always 2
- Minimum server count for single+activefailover is always 2
- Members in phase CleanoutServer are reverted to Created when cleanout action fails and causes the reconciliation plan to abort.
fixes #178
> Min dbserver count is 2. Revert phase when cleanout has failed

- pkg/apis/deployment/v1alpha/plan.go
- pkg/deployment/access_package.go
- pkg/deployment/context_impl.go
- pkg/deployment/reconcile/action_context.go
- pkg/deployment/reconcile/action_renew_tls_ca_certificate.go
- pkg/deployment/reconcile/action_rotate_member.go
- pkg/deployment/reconcile/context.go
- pkg/deployment/reconcile/plan_builder.go
- pkg/deployment/reconcile/plan_builder_test.go
- pkg/deployment/reconcile/plan_builder_tls.go
- pkg/deployment/reconcile/plan_executor.go
- pkg/deployment/reconcile/timeouts.go
- pkg/deployment/resources/certificates_client_auth.go
- pkg/deployment/resources/certificates_tls.go
- pkg/util/k8sutil/secrets.go
This PR added the replacement of a TLS CA certificate for deployments when:
- The CA certificate is close to its expiration date (90% of lifetime)
- The alternate names given in `spec.tls.altNames` are not found in the certificate. (have been changed by user)
fixes #164
> Added renewal of deployment TLS CA certificate

- examples/arango-local-storage.yaml
- pkg/apis/deployment/v1alpha/plan.go
- pkg/apis/deployment/v1alpha/server_group_spec.go
- pkg/deployment/context_impl.go
- pkg/deployment/reconcile/action.go
- pkg/deployment/reconcile/action_add_member.go
- pkg/deployment/reconcile/action_cleanout_member.go
- pkg/deployment/reconcile/action_context.go
- pkg/deployment/reconcile/action_remove_member.go
- pkg/deployment/reconcile/action_renew_tls_ca_certificate.go
- pkg/deployment/reconcile/action_renew_tls_certificate.go
- pkg/deployment/reconcile/action_rotate_member.go
- pkg/deployment/reconcile/action_shutdown_member.go
- pkg/deployment/reconcile/action_upgrade_member.go
- pkg/deployment/reconcile/action_wait_for_member_up.go
- pkg/deployment/reconcile/context.go
- pkg/deployment/reconcile/plan_builder.go
- pkg/deployment/reconcile/plan_builder_storage.go
- pkg/deployment/reconcile/plan_builder_test.go
- pkg/deployment/reconcile/plan_executor.go
- pkg/util/k8sutil/events.go
This PR adds support for changing the `storageClassName` of a server group (`agents`, `dbserver` or `single` in `ActiveFailover` mode)
> Allow changing server group storage class.

- main.go
- pkg/deployment/deployment.go
- pkg/deployment/members.go
- pkg/deployment/reconcile/context.go
- pkg/deployment/resources/context.go
- pkg/deployment/resources/pod_inspector.go
- pkg/operator/operator_deployment.go
- pkg/operator/operator_deployment_relication.go
- pkg/operator/operator_local_storage.go
- pkg/replication/deployment_replication.go
- pkg/storage/local_storage.go
- pkg/util/k8sutil/events.go
This PR replaced the custom `events.Create` with a more standard `record.EventRecord` to create events.
The benefit of this is that this enables event compression: When multiple events of the same type&reason are created in succession, the count is increased instead of created more and more events.
> Use standard EventRecord to use event compression

- docs/Manual/Deployment/Kubernetes/DeploymentResource.md
- pkg/apis/deployment/v1alpha/deployment_spec.go
- pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
- pkg/deployment/reconcile/plan_builder.go
- pkg/deployment/reconcile/plan_builder_storage.go
- pkg/deployment/reconcile/plan_builder_tls.go
- pkg/util/k8sutil/events.go
> Adding downtimeAllowed field

- docs/Manual/Tutorials/Kubernetes/DC2DC.md
This PR adds a tutorial for configuring dc2dc on kubernetes.
This PR assumes the code of #186
> Added tutorial for configuring DC2DC of Kubernetes

- docs/Manual/Deployment/Kubernetes/Authentication.md
- docs/Manual/Deployment/Kubernetes/DeploymentReplicationResource.md
- docs/Manual/Deployment/Kubernetes/DeploymentResource.md
- docs/Manual/Deployment/Kubernetes/DriverConfiguration.md
- docs/Manual/Deployment/Kubernetes/Troubleshooting.md
Only typos so far, might have to fix a few Gitbook related issues as well.
> Documentation fixes

- pkg/operator/operator_leader.go
- pkg/util/constants/constants.go
This PR sets a label (`role=leader`) on the operator Pod who won the leader election.
After this, fetching the logs of the leader deployment operator looks like this
```
kubectl logs --selector=name=arango-deployment-operator,role=leader
```
> Set a `role=leader` label on the Pod who won the leader election

- pkg/apis/deployment/v1alpha/deployment_spec_test.go
- pkg/apis/deployment/v1alpha/server_group_spec.go
- pkg/deployment/deployment.go
This PR fixes a problem where a `mode` field was not reset, because the validation of the spec after applying ResetImmutableFields failed.
> Applying defaults after immutable fields have been reset

- tests/upgrade_test.go
> Updated versions to known "proper" versions

- docs/Manual/Deployment/Kubernetes/DriverConfiguration.md
The load balancer support is currently in devel in the main repo. It will be back-ported to 3.3 for sure, but has not been done yet. Do the docs here apply for 3.3? 3.2?
> Adjust documentation based on new load balancer support.

- pkg/apis/deployment/v1alpha/deployment_status.go
- pkg/apis/deployment/v1alpha/plan.go
- pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
- pkg/deployment/reconcile/action_context.go
- pkg/deployment/reconcile/action_upgrade_current_image.go
- pkg/deployment/reconcile/plan_builder.go
- pkg/deployment/reconcile/plan_executor.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/server_api.go
- pkg/util/k8sutil/events.go
Before a new Pod would always use the image given in the spec of an `ArangoDeployment`.
That could lead to scaling up to new (and unintended) versions.
With this PR a new `current-image` field is added to the status of an `ArangoDeployment`.
When a pod is created, the `current-image` is used. When upgrading, the `current-image` field is updated first, if confirmed that an upgrade is indeed allowed.
If an upgrade is not allowed, an event is added to the `ArangoDeployment`.
> Use new CurrentImage field to prevent unintended upgrades.

- pkg/deployment/reconcile/plan_builder.go
- pkg/util/k8sutil/events.go
"Upgrading" enterprise to community edition is not allowed
> Include license in upgrade check

- README.md
This PR must be merged just before the first release that contains #255.
DO NOT MERGE BEFORE A NEW RELEASE.
> README updates, removing `kubectl apply -f crd.yaml`

- docs/Manual/Deployment/Kubernetes/DeploymentResource.md
- pkg/apis/deployment/v1alpha/deployment_spec.go
- pkg/apis/deployment/v1alpha/deployment_spec_test.go
- pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
- pkg/deployment/images.go
- pkg/deployment/resources/pod_creator.go
http://c11:8080/job/kube-arangodb-branches/job/feature%252Fdisable-ipv6/
> Added `disableIPV6` Spec entry.

- Makefile
- tests/load_balancer_test.go
- tests/test_util.go
Skip LoadBalancer test if the cluster was unable to deploy a LoadBalancer.
> Skip LoadBalancer Test

- pkg/apis/deployment/v1alpha/member_status_list.go
- pkg/deployment/cluster_scaling_integration.go
- pkg/deployment/reconcile/plan_builder.go
- pkg/deployment/resources/secret_hashes.go
Do not update the agency if not required. This could reset some user input.
> Bug fix/scale up error

- Makefile
- tests/load_balancer_test.go
- tests/test_util.go
Reverts arangodb/kube-arangodb#269
> Revert "Skip LoadBalancer Test"

- pkg/deployment/cluster_scaling_integration.go
Previously the spec was updated every two seconds with the values written in the agency. This was due to a change that was done so that the operator will respect the ui after being redeployed.
The root cause seems to be a uninitialised lastNumberOfServers struct.
Ignore debug output.
> Fixing uninitialised `lastNumberOfServers`.

- pkg/deployment/images.go
- pkg/util/k8sutil/images.go
Fixed image ID retrieval issue occurring when sidecars were injected where the sidecar's ID was being retrieved instead of ArangoDB in platforms such as Istio.  See issue: #260
> Fixing imageID retrieval issue when sidecars are injected.

- pkg/apis/deployment/v1alpha/deployment_status.go
- pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
- pkg/deployment/deployment.go
- pkg/deployment/reconcile/action_remove_member.go
Added secret force-status-reload status field. ✌️
> Fix Reload

- docs/Manual/Tutorials/Kubernetes/README.md
The tutorial did not work for me before. Using the commands in the main README gets me further along.
> Uses new commands in tutorial

- docs/Manual/Deployment/Kubernetes/Drain.md
Internal Ref:
- https://github.com/arangodb/planning/issues/3733
> Make cleanoutserver step mandatory in drain documentation.

- pkg/deployment/deployment_inspector.go
- pkg/deployment/reconcile/reconciler.go
- pkg/deployment/resources/pod_inspector.go
If all members are dropped, create a new one.
> Coordinators

- pkg/deployment/reconcile/plan_builder_storage.go
- pkg/deployment/resources/pvc_inspector.go
- pkg/util/k8sutil/events.go
- pkg/util/k8sutil/pvc.go
- tests/persistent_volumes_test.go
Added test for volume resize. Added code to do so.
> Volume resizing

- deps/github.com/arangodb/go-driver/jwt/jwt.go
- pkg/deployment/resources/pod_creator.go
Do not use super user token but restricted token for liveness and readiness.
> Special Probe Tokens

- pkg/deployment/context_impl.go
- pkg/deployment/deployment.go
- pkg/deployment/reconcile/action_wait_for_member_up.go
- pkg/deployment/reconcile/context.go
- pkg/deployment/reconcile/plan_builder.go
- pkg/deployment/reconcile/plan_builder_context.go
- pkg/deployment/reconcile/timeouts.go
- pkg/deployment/resources/deployment_health.go
- pkg/deployment/resources/pod_inspector.go
- pkg/deployment/resources/resources.go
Monitor sync status concurrently. Only create new upgrade plan if everything is good.
> waitForSync Upgrade

- pkg/deployment/resources/deployment_health.go
This fixes a test and is benficial otherwise, too.
> Only check shard sync status for cluster deployments.

- README.md
**do not merge yet**
---
**Fixes:**
- bare metal 1.10 is production ready
**Other:**
- adds entries for 1.11, 1.12, 1.13 and 1.14 for bare metals
- adds IBM Cloud
- adds operator version
Next steps (for **later**):
- the table should be part of the official doc - a link can be included in the repo readme and the actual content moved to doc/ for integration into the official manual
- we should reconsider 3.3.13 imho, and add a later version instead
Thanks,
> Supported versions

- Makefile
As the codegen is rather expensive it makes sense to check the variables before.
> Check variables before codegen.

- pkg/apis/deployment/v1alpha/member_status_list.go
- pkg/apis/deployment/v1alpha/member_status_list_test.go
- pkg/deployment/resources/member_cleanup.go
Fixed problem in MemberStatusList.Equal that causes the MemberOfCluster condition to be left out (in some cases).
It will also avoid updating the status of an ArangoDeployment in other cases.
> Bug fix/unreliable cluster membership

- pkg/server/server.go
Disabled debug mode of gin to remove confusing log message.
> Disable GIN-Debug

- pkg/deployment/resources/pod_termination.go
- tests/upgrade_test.go
When the member is terminated do not set cleaned out state when resigning. Added test for upgrade.
> Resign Leadership Bugfix

- chart/kube-arangodb/templates/NOTES.txt
- chart/kube-arangodb/templates/deployment.yaml
- manifests/arango-deployment-replication.yaml
- manifests/arango-deployment.yaml
- manifests/arango-storage.yaml
Also created NOTES.txt - example helm output:
```NOTES:
You have installed Kubernetes ArangoDB Operator in version 0.3.16
To access ArangoDeployments you can use:
kubectl --namespace "release-namespace" get arangodeployments
More details can be found on https://github.com/arangodb/kube-arangodb/tree/0.3.16/docs
```
Links gonna be updated using "release" scripts
> Drop Security Context

- main.go
- pkg/util/k8sutil/owner.go
https://github.com/arangodb/kube-arangodb/issues/461
**For the time being, we can not use apiextensions.k8s.io/v1beta1 because it is in k8s.io version 1.16. We are using k8s.io version 1.12**
k8s.io/api/policy/v1beta1 can not be changed because it is the latest version in k8s.io 1.12
> Change k8s.io version to v1

- pkg/util/k8sutil/constants.go
- pkg/util/k8sutil/services.go
- pkg/util/k8sutil/storageclass.go
- pkg/util/k8sutil/storageclass_test.go
IBM CV `NoAlphaAnnotations` issue
> Discard beta phrases from annotations

- pkg/util/k8sutil/affinity.go
- pkg/util/k8sutil/affinity_test.go
IBM CV `PodHasArchBasedNodeAffinity` issue - created pods needs to have arch-based node affinity
> Add node affinity for members pod

- pkg/util/k8sutil/pods.go
- scripts/kube_create_backup_remote_secret.sh
- scripts/kube_create_license_key_secret.sh
- tests/backup_test.go
- tests/load_balancer_test.go
- tests/pc_test.go
IBM CV requires that created pods need to have dropped all capabilities.
Tested on arangodb/enterprise:3.5.2 with full integration test.
> Drop all capabilities for security context

- pkg/util/k8sutil/pods.go
- reboot.go
It is a fix for https://github.com/arangodb/kube-arangodb/pull/497
> Drop capabilities for most of containers

- pkg/deployment/deployment_test.go
- pkg/deployment/images.go
- pkg/deployment/images_test.go
- pkg/deployment/resources/certificates_tls.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/resources/pod_creator_arangod.go
- pkg/deployment/resources/pod_creator_sync.go
- pkg/deployment/resources/pod_inspector.go
- pkg/util/k8sutil/affinity.go
- pkg/util/k8sutil/affinity_test.go
- pkg/util/k8sutil/lifecycle.go
- pkg/util/k8sutil/pods.go
- reboot.go
Unit tests:
I wrote 50 unit tests with different scenarios for `EnsurePods` and `ensureImages` and those tests pass on my branch and on the temporary branch `testing/after-cleaning` (I created from master that only for testing because I had to export a few functions and create short helpful functions, we can assume that branch is the same like master. Compare testing branch with master: https://github.com/arangodb/kube-arangodb/compare/testing/after-cleaning)
Integration tests:
Full integration tests passed with image `arangodb/enterprise-preview:3.5.3`
> Cleaning the code

- go.mod
- pkg/deployment/pod/args.go
- pkg/deployment/pod/pair.go
- pkg/deployment/pod/upgrade.go
- pkg/deployment/reconcile/plan_builder_test.go
- pkg/deployment/resources/exporter.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/resources/pod_creator_coordinator_args_test.go
Fixes https://github.com/arangodb/kube-arangodb/issues/509
> Feature/cluster upgrade for 3.6

- CHANGELOG.md
- pkg/deployment/reconcile/action_recreate_member.go
- pkg/deployment/reconcile/plan_builder.go
- pkg/deployment/reconcile/plan_builder_test.go
Difference between action `ActionTypeRemoveMember + ActionTypeAddMember` and `ActionTypeRecreateMember` is that action `ActionTypeRecreateMember` will not recreate PVC and Member ID - very useful in Ceerdinators to not create zombie Coordinators in cluster and for Agency to persist data in corner cases.
> [Feature] Do not remove Agency members

- CHANGELOG.md
- main.go
- pkg/logging/logger.go
- storage.go
Allow to specify logger overrides in ArangoDB format for Operator internal loggers.
> [Feature] Enable logger overrides

- examples/cluster1-with-sync.yaml
- examples/cluster2-with-sync.yaml
- examples/production-cluster-with-metrics.yaml
- examples/production-cluster.yaml
- examples/reboot-pod.yaml
- examples/simple-cluster-with-metrics.yaml
- examples/simple-cluster.yaml
- examples/single-server.yaml
Patched the examples for kube-arangodb to ArangoDB version `3.7.11` and the metrics exporter to version `0.1.8`
> Patched examples for latest ArangoDB & exporter

- CHANGELOG.md
- pkg/apis/deployment/v2alpha1/deployment_spec.go
- pkg/apis/deployment/v2alpha1/server_group.go
- pkg/apis/deployment/v2alpha1/zz_generated.deepcopy.go
- pkg/deployment/context_impl.go
- pkg/deployment/deployment.go
- pkg/deployment/deployment_inspector.go
- pkg/deployment/deployment_suite_test.go
- pkg/deployment/resources/context.go
Persist name and namespace of deployment to prevent issues when K8S API cannot be contacted
> [Bugfix] Use persistent name and namespace

- CHANGELOG.md
- pkg/deployment/deployment.go
- pkg/deployment/resources/pod_finalizers.go
- pkg/util/k8sutil/pods.go
Fixes: https://github.com/arangodb/kube-arangodb/issues/748
> [Bugfix] Adjust pod finalizers

- Makefile
- pkg/apis/deployment/v1/plan.go
- pkg/apis/deployment/v2alpha1/plan.go
- pkg/deployment/reconcile/action_helper.go
- pkg/deployment/reconcile/action_runtime_container_args_udpate.go
- pkg/deployment/reconcile/plan_executor.go
- pkg/deployment/rotation/arangod_containers.go
- pkg/deployment/rotation/arangod_containers_test.go
- pkg/deployment/rotation/check.go
- pkg/deployment/rotation/compare.go
- pkg/deployment/rotation/utils_test.go
- pkg/util/k8sutil/pair.go
- pkg/util/k8sutil/pair_test.go
- pkg/util/strings.go
- pkg/util/strings_test.go
test: https://github.com/arangodb/kube-arangodb-test/pull/29
> [Feature] change log level on the fly

- CHANGELOG.md
- README.md
- pkg/deployment/deployment_core_test.go
- pkg/deployment/deployment_definitions_test.go
- pkg/deployment/deployment_encryption_test.go
- pkg/deployment/deployment_metrics_test.go
- pkg/deployment/deployment_suite_test.go
- pkg/deployment/features/features.go
- pkg/deployment/features/local.go
- pkg/deployment/features/metrics.go
Test https://github.com/arangodb/kube-arangodb-test/pull/28
> [Feature] Always use internal metrics exporter

- pkg/deployment/images.go
Preparation for arangosync-v2 - part1
> Create container identity for arangosync-v2

- pkg/deployment/images.go
- pkg/deployment/pod/volumes.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/resources/pod_creator_arangod.go
- pkg/deployment/resources/pod_creator_sync.go
- pkg/util/k8sutil/interfaces/pod_creator.go
- pkg/util/k8sutil/pods.go
add 4 new functions to the interfaces:
GetArgs
GetName
GetVolume
GetVolumeMounts
> [Feature] Refactor Pod and containter creator part2

- pkg/deployment/images.go
- pkg/deployment/resources/pod_creator.go
- pkg/deployment/resources/pod_creator_arangod.go
- pkg/deployment/resources/pod_creator_sync.go
- pkg/util/k8sutil/interfaces/pod_creator.go
This PR will help to use the function:
```
func (m *MemberArangoDPod) Init(_ context.Context, _ interfaces.Inspector, pod *core.Pod) error {
```
in the future to recognize if the worker sidecar can be created together with the DB server
> [Refactor] Init pod creator with an error

- CHANGELOG.md
- pkg/apis/deployment/v1/plan.go
- pkg/apis/deployment/v2alpha1/plan.go
- pkg/deployment/reconcile/plan_executor.go
it was merged into the 1.2.8 branch, but branch 1.2.8 was removed
> [Feature] Add metrics for the current plan actions

- Makefile
It was installing globally instead of installing into .gobuild subdir.
The problem was introduced here: https://github.com/arangodb/kube-arangodb/commit/071c837f2bc6111ade71efd17afb457a199659b0#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L394
> [bugfix] Fix golangci-lint tool local installation

- CHANGELOG.md
- chart/arangodb-ingress-proxy/templates/deployment.yaml
- chart/kube-arangodb/templates/deployment.yaml
There is still a backward compatibility support for `beta.kubernetes.io/arch` in v1 and v2alpha APIs (architecture.go)
> Replace `beta.kubernetes.io/arch` to `kubernetes.io/arch` in charts

- CHANGELOG.md
- pkg/deployment/agency/cache.go
- pkg/deployment/agency/config.go
- pkg/deployment/agency/config_test.go
- pkg/deployment/context_impl.go
- pkg/deployment/deployment.go
- pkg/deployment/deployment_inspector.go
- pkg/deployment/reconcile/action_context.go
- pkg/deployment/reconcile/plan_builder_test.go
- pkg/deployment/reconciler/context.go
- pkg/deployment/resources/pod_leader.go
- pkg/deployment/resources/services.go
- pkg/util/k8sutil/services.go
- pkg/util/k8sutil/util.go
test: https://github.com/arangodb/kube-arangodb-test/pull/84
> [Feature] Add agency leader service

- pkg/deployment/deployment.go
- pkg/deployment/deployment_inspector.go
- pkg/deployment/resources/annotations.go
- pkg/deployment/resources/inspector/inspector.go
- pkg/deployment/resources/labels.go
- pkg/operator/operator_deployment.go
current log output when `log.level=trace`:
```
2022-06-28T13:47:35Z DBG Looking for ServiceMonitor CRD... name=deployment namespace=jakubwierzbowski operator-id=lw7qq
2022-06-28T13:47:35Z INF ...have discovered ServiceMonitor CRD name=deployment namespace=jakubwierzbowski operator-id=lw7qq
2022-06-28T13:47:35Z DBG Initially inspect deployment... name=deployment namespace=jakubwierzbowski operator-id=lw7qq
2022-06-28T13:47:35Z TRC Pre-inspector refresh start name=deployment namespace=jakubwierzbowski operator-id=lw7qq
2022-06-28T13:47:35Z TRC Inspector refresh start name=deployment namespace=jakubwierzbowski operator-id=lw7qq
2022-06-28T13:47:35Z TRC Inspector refresh component=ServiceMonitor name=deployment namespace=jakubwierzbowski operator-id=lw7qq
2022-06-28T13:47:35Z TRC Inspector …
```
> Move irrelevant logs to TRACE level

- CHANGELOG.md
- cmd/cmd.go
- cmd/crd.go
- pkg/crd/apply.go
The `EnsureCRD` implementation was slightly adjusted to return error if requested, so the command can exit with 1 if the problem occurs.
> [Feature] GT-40 Add 'crd install' subcommand

- pkg/deployment/metrics.go
The value wasn't used in metrics
> Fix the reporting of DeploymentImmutableErrors counter on metrics

- CHANGELOG.md
Features marked as released a long time ago but they are not released yet
> Fix CHANGELOG: two entries were misplaced during merge

- CHANGELOG.md
- Makefile
- pkg/apis/deployment/v1/conditions.go
- pkg/deployment/member/phase_updates.go
- pkg/deployment/members.go
- pkg/deployment/reconcile/plan_builder_context.go
- pkg/deployment/reconcile/plan_builder_rotate_arch.go
- pkg/util/k8sutil/events.go
This validation handles two cases:
1. `arch` annotation - we will not let the change arch in member if ArangoDB image is below 3.10
2. member creation - we will change the member arch to the AMD64 if ArangoDB image is below 3.10
> GT-137 image validation for AMD64 arch

- CHANGELOG.md
- pkg/deployment/agency/cache.go
Covers: https://github.com/arangodb/kube-arangodb/issues/1174
> [Bugfix] Move Agency CommitIndex log message to Trace

- CHANGELOG.md
- pkg/apis/replication/v1/collection_status.go
- pkg/apis/replication/v1/database_status.go
- pkg/apis/replication/v1/endpoint_status.go
- pkg/apis/replication/v1/replication_status.go
- pkg/apis/replication/v1/shard_status.go
- pkg/apis/replication/v2alpha1/collection_status.go
- pkg/apis/replication/v2alpha1/database_status.go
- pkg/apis/replication/v2alpha1/endpoint_status.go
- pkg/apis/replication/v2alpha1/replication_status.go
- pkg/apis/replication/v2alpha1/shard_status.go
- pkg/replication/sync_inspector.go
These two fields might be too big - exceeding k8s limits. e.g. one of customers has 10k shards - there will be at least about `10000*2*50=1MB` of data
> Don't serialize and deprecate two DeploymentReplicationStatus fields

- CHANGELOG.md
- pkg/apis/replication/v1/database_synchronization_status.go
- pkg/apis/replication/v1/synchronization_status.go
- pkg/apis/replication/v2alpha1/database_synchronization_status.go
- pkg/apis/replication/v2alpha1/synchronization_status.go
- pkg/replication/sync_inspector.go
Deprecate `ShardsTotal` and `ShardsInSync`  fields. Clients should use new `Progress` field directly instead of calculating it. (also ShardsTotal might have incorrect value when starting replication of huge dataset)
> [Improvement] GT-228 Add new field to CR for more precise calculation of DC2DC replication progress

- CHANGELOG.md
- pkg/deployment/resources/pod_creator_sync.go
If customer uses "Type=Managed" for `SyncExternalAccessSpec` AND uses headless service (`ClusterIP=None`) then sync pods won't be created due to an error while creating a HostAlias for pod.
The code in `syncHostAlias` method still not perfect because it assumes that EA service name would be always `<depl-name>-sync`. That should be fixed in separate ticket.
> Fix creating sync components with EA type set to Managed and headless svc

- examples/cluster1-with-sync.yaml
- examples/cluster2-with-sync.yaml
- examples/production-cluster-with-metrics.yaml
- examples/production-cluster.yaml
- examples/reboot-pod.yaml
- examples/simple-cluster-with-metrics.yaml
- examples/simple-cluster.yaml
- examples/single-server.yaml
- scripts/patch_examples.sh
set to 3.10.6 because 3.11.0 has some known issues. In most cases it is better to use 3.10 branch until 3.11.1 is not released.
> [Maintenance] GT-435 | Update ArangoDB version used in examples YAMLs

- CHANGELOG.md
- pkg/apis/deployment/v1/plan_locals.go
- pkg/apis/deployment/v2alpha1/plan_locals.go
- pkg/deployment/agency/definitions.go
- pkg/deployment/agency/state/state.go
- pkg/deployment/agency/state/state_test.go
- pkg/deployment/reconcile/action_resign_leadership.go
- pkg/deployment/reconcile/helper_wrap.go
- pkg/deployment/reconcile/plan_builder_rotate_upgrade.go
- pkg/deployment/reconcile/plan_builder_rotate_upgrade_decision.go
- pkg/deployment/reconcile/plan_builder_utils.go
- pkg/util/refs.go
- pkg/util/refs_test.go
no automated tests for it. I did some manual tests where I restarted DB server when it was in restarting phase, so operator was able to log information about this fact.
When leader's shards must be moved from one DB server to another, then resign leadership action must be performed.
Operator requests for it and checks progress. In the meantime, it may occur that DB server is restarted and action will not be finished in some timeout ~1 hour. With this PR, this action will be removed immediately whenever it occurs.
> [Feature] Abort resignation of leadership when dbserver restarted

- CHANGELOG.md
- Makefile
'echo' command is not portable and should be avoided since it can have different parameters supported depending of the shell
> Fix make manifests-crd-file command

- Makefile
currently `make yamlfmt` does not print out which file has incorrect formatting
> Print yaml file which is not formatted properly

- .circleci/config.yml
- .circleci/continue_config.yml
- .gitignore
- Makefile
- manifests/kustomize-enterprise/k2kclustersync/kustomization.yaml
- CircleCI now uses Dynamic configuration to filter for modified files https://circleci.com/docs/using-dynamic-configuration/
- When manifests or chart file changes, additional workflow will be execute which will spin up minikube and try to apply manifests
- Fixed one issue found in customize for EE
> [Maintenance] Add CircleCI workflow to verify manifests - GT-493

- README.md
- docs/generated/actions.md
- docs/generated/metrics/README.md
- internal/md/sections.go
Reason: old markers `` are not compatible with Jekyll static site generator, e.g. see https://arangodb.github.io/kube-arangodb/ page. First table is generated with new markers `[START_INJECT]: # (limits)` and other tables are generated with old markers.
Please note that new markers require an empty line before and after the marker.
> (Documentation) Use Jekyll-compatible markers for section injection

- CHANGELOG.md
- docs/api/ArangoBackup.V1.md
- docs/api/ArangoBackupPolicy.V1.md
- docs/api/ArangoDeployment.V1.md
- docs/api/ArangoDeploymentReplication.V1.md
- docs/api/ArangoLocalStorage.V1Alpha.md
- docs/api/ArangoMember.V1.md
- internal/docs_test.go
- we are currently using type names in field header. That causes the URL hashes to look like `#specsomefield-string`. But old documentation use `#specsomefield` format. We should use same format to ensure old external links will work properly
- also improving overall page layout: separator is added between fields + source code reference in inlined and looks more compact.
> (Documentation)  Do not use field type name for field URL hash

- docs/api/ArangoMLExtension.V1Alpha1.md
- docs/api/ArangoMLStorage.V1Alpha1.md
- internal/cr_validation_test.go
- internal/docs_parser_test.go
- internal/docs_test.go
- internal/schema_builder_test.go
- pkg/crd/crds/ml-storage.schema.generated.yaml
- proper parsing for FileSet tokens
- use full package path for field names
- ignore zz_generated files during parsing
> Fix doc and schema validation for shared objects

- CHANGELOG.md
- go.mod
- go.sum
- pkg/util/fwatch/watcher.go
Previous lib was not compiling on MacOS
> Switch to fsnotify

- pkg/deployment/old_metrics.go
Reverts metrics loading logic changed in the: https://github.com/arangodb/kube-arangodb/pull/1470
> Revert old logic for arango_operator_deployment_agency_state metric

- docs/backup-resource.md
fixes the documentation after downloads / uploads failed with slashes in url.
> s3 url must not inlude slashes

- docs/upgrading.md
Upgrade procedure to enterprise from community
> [Documentation] Add upgrade procedure from community to enterprise
