pkg/apis/deployment/v1alpha/tls_spec.go
pkg/apis/deployment/v1alpha/tls_spec_test.go

Fixed validation of tls.caSecretName=None

---

pkg/logging/logger.go

This eases reading the logs when they are collected in CI or other tools

Disabled colorizing logs

---

tests/auth_test.go
tests/cursor_test.go
tests/db_util.go
tests/member_resilience_test.go
tests/resilience_test.go
tests/rocksdb_encryption_test.go
tests/scale_test.go
tests/simple_test.go

[ci LONG=1] [ci TESTOPTIONS="-test.run ^TestCursor"]

Added tests for query cursors on various deployments.

---

Makefile

Using GOCACHE feature of go 1.10.

Make use of GOCACHE as docker volume for improved build times

---

docs/design/testing.md
pkg/storage/pv_cleanup.go
pkg/storage/pv_inspector.go
tests/persistent_volumes_test.go

This PR aims to add tests for persistent volumes. Detailed information can be found in the [test design document](https://github.com/arangodb/kube-arangodb/blob/test/peristent-volumes/docs/design/testing.md).

add persistent-volume tests

---

pkg/deployment/members.go
pkg/util/k8sutil/names.go

Fix prefix of internal ID's generated for single servers.

Fixed ID prefix for single servers

---

docs/Manual/Tutorials/Kubernetes/DC2DC.md

See https://github.com/arangodb/arangodb/pull/5921#issuecomment-406028317

EE note for Kubernetes DC2DC

---

pkg/deployment/resources/pod_creator.go

Unified readiness test. Now using `_api/version` only.

Unified Readiness Test

---

pkg/storage/pv_creator.go

Show the correct volume size for volumes provided by the storage operator.

StorageOperator Volume Size Fix

---

pkg/deployment/reconcile/action_wait_for_member_up.go

Wait for coordinator to be ready in kubernetes.

Coordinator upgrade downtime

---

pkg/deployment/images.go
pkg/deployment/reconcile/plan_builder.go
pkg/deployment/resources/pod_creator.go
pkg/util/k8sutil/images.go
pkg/util/k8sutil/pods.go

Forward resources to container, except for Storage.

Container Resources

---

pkg/apis/deployment/v1alpha/server_group_spec.go
pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
pkg/deployment/images.go
pkg/deployment/resources/pod_creator.go
pkg/util/k8sutil/pods.go

Added user sidecars.

---

pkg/deployment/reconcile/action_remove_member.go

Ignore connection errors when removing server.

---

README.md

Please do **not** merge yet - wait the final GO from @lservini 
Adds IBM Cloud on k8s version 1.12

Updates list of supported versions - IBM Cloud

---

.gitignore
docs/Manual/Deployment/Kubernetes/DeploymentResource.md
pkg/apis/deployment/v1alpha/deployment_spec.go
pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
pkg/deployment/images.go
pkg/deployment/resources/pod_creator.go
pkg/util/k8sutil/pods.go

Allow to set ImagePullSecrets in pods

---

docs/Manual/Deployment/Kubernetes/DeploymentResource.md
pkg/apis/deployment/v1alpha/deployment_spec.go
pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
pkg/deployment/resources/pod_termination.go

And change logic: default now false and meaning reversed.

Rename LocallyAttachedVolumes to NetworkAttachedVolumes.

---

tests/version_test.go

Compare version using ArangoVersion type

Add test which checks if version has been changed

---

tests/sidecar_test.go

Fix sidecar test definitions. The latest image was used by mistake

Fix sidecar tests

---

pkg/deployment/reconcile/plan_builder_tls.go

Ignore certs from server response if they are part of CA Chain

[Bugfix] Ignore not owned CAs

---

examples/production-cluster-with-metrics.yaml

Fix production-cluster-with-metrics.yaml

---

examples/cluster1-with-sync.yaml
examples/cluster2-with-sync.yaml
examples/production-cluster-with-metrics.yaml
examples/production-cluster.yaml
examples/simple-cluster-with-metrics.yaml
examples/simple-cluster.yaml
examples/single-server.yaml

Updated the included examples to our latest ArangoDB 3.7.12 release.

Update examples to ArangoDB 3.7.12

---

CHANGELOG.md
pkg/deployment/resources/member_cleanup.go
pkg/deployment/resources/secrets.go
pkg/deployment/resources/services.go
pkg/util/k8sutil/inspector/arangomember/member.go
pkg/util/k8sutil/reconcile.go

[Bugfix] Fix ArangoMember management

---

pkg/apis/deployment/v1/server_group.go
pkg/apis/deployment/v1/server_group_containers.go
pkg/apis/deployment/v1/server_group_spec.go
pkg/apis/deployment/v1/sync_spec.go
pkg/apis/deployment/v2alpha1/server_group.go
pkg/apis/deployment/v2alpha1/server_group_containers.go
pkg/apis/deployment/v2alpha1/server_group_spec.go
pkg/apis/deployment/v2alpha1/sync_spec.go
pkg/deployment/deployment_inspector.go
pkg/deployment/deployment_suite_test.go
pkg/deployment/features/arangosync_v2.go
pkg/deployment/images.go
pkg/deployment/images_test.go
pkg/deployment/pod/utils.go
pkg/deployment/reconcile/plan_builder_scale.go
pkg/deployment/resources/annotations.go
pkg/deployment/resources/exporter.go
pkg/deployment/resources/labels.go
pkg/deployment/resources/member_cleanup.go
pkg/deployment/resources/pod_creator.go
pkg/deployment/resources/pod_creator_arangod.go
pkg/deployment/resources/pod_creator_probes.go
pkg/deployment/resources/pod_creator_sync.go
pkg/deployment/resources/services.go
pkg/util/k8sutil/constants.go
pkg/util/k8sutil/pods.go

tests: https://github.com/arangodb/kube-arangodb-test/pull/50

[Feature] worker as a sidecar

---

CHANGELOG.md
pkg/apis/deployment/v1/plan.go
pkg/apis/deployment/v2alpha1/plan.go
pkg/deployment/reconcile/plan_executor.go

created metrics for the current number of actions

[Feature] Add metrics for the plan actions

---

CHANGELOG.md
pkg/apis/deployment/annotations.go
pkg/apis/deployment/v1/conditions.go
pkg/apis/deployment/v1/plan.go
pkg/apis/deployment/v2alpha1/conditions.go
pkg/apis/deployment/v2alpha1/plan.go
pkg/deployment/chaos/context.go
pkg/deployment/chaos/monkey.go
pkg/deployment/context_impl.go
pkg/deployment/reconcile/action.go
pkg/deployment/reconcile/action_context.go
pkg/deployment/reconcile/action_kill_member_pod.go
pkg/deployment/reconcile/action_remove_member.go
pkg/deployment/reconcile/action_rotate_member.go
pkg/deployment/reconcile/action_rotate_start_member.go
pkg/deployment/reconcile/action_shutdown_member.go
pkg/deployment/reconcile/context.go
pkg/deployment/reconcile/helper_shutdown.go
pkg/deployment/reconcile/plan_builder_test.go
pkg/deployment/reconcile/reconciler.go
pkg/deployment/resources/context.go
pkg/deployment/resources/member_cleanup.go

tests: https://github.com/arangodb/kube-arangodb-test/pull/53

[Feature] Kill pod forcefully when annotation is set

---

docs/bare-metal.md
docs/design/metrics.md
examples/metrics/deployment-operator-servicemonitor.yaml

- standard Prometheus installation (no-TLS)
- standard Prometheus installation (TLS)
- Prometheus Operator installation

Add docs about integration operator metrics and Prometheus

---

pkg/deployment/context_impl.go
pkg/deployment/reconcile/action_context.go
pkg/deployment/reconcile/plan_builder_rotate_upgrade.go
pkg/deployment/reconcile/plan_builder_test.go
pkg/deployment/reconciler/context.go
pkg/deployment/resources/pod_creator.go

there is unused code which is very annoying when reviewing to code.

[Refactor] remove unused code

---

CHANGELOG.md
pkg/deployment/reconcile/condition_member_recreation.go

tests: https://github.com/arangodb/kube-arangodb-test/pull/107

[Feature] Shrink agent volume condition

---

CHANGELOG.md
docs/design/README.md
docs/design/configuring_tz.md

[docs] GT-132 Add docs on setting timezone for containers

---

cmd/cmd.go
pkg/deployment/features/local.go

[Bugfix] fix for creating features' configmap

---

CHANGELOG.md
pkg/apis/deployment/v1/conditions.go
pkg/apis/deployment/v2alpha1/conditions.go
pkg/deployment/access_package.go
pkg/deployment/agency/cache.go
pkg/deployment/agency/definitions.go
pkg/deployment/agency/state.go
pkg/deployment/deployment.go
pkg/deployment/reconcile/action_context.go
pkg/deployment/reconcile/plan_builder_high.go
pkg/deployment/reconcile/plan_builder_scale.go
pkg/deployment/reconcile/plan_builder_sync.go
pkg/deployment/reconcile/plan_builder_test.go
pkg/deployment/reconcile/plan_builder_tls.go
pkg/deployment/reconciler/context.go
pkg/deployment/resources/pdbs.go
pkg/deployment/resources/pod_inspector.go
pkg/deployment/resources/secret_hashes.go
pkg/deployment/resources/secrets.go
pkg/deployment/resources/services.go

Manual tests went fine:
- ArangoDeploymentReplication was removed so agency was updated to inactive sync.
- service deployment-sync was removed.
- as a last step ArangoSync pods were removed.

[Bugfix] Do not stop Sync if Synchronization is in progress

---

CHANGELOG.md
go.mod
go.sum
pkg/replication/finalizers.go
pkg/replication/sync_inspector.go

Required for next PR about reporting sync progress.

GT-228 Update arangosync-client package for new API capabilities and better HTTP handling

---

CHANGELOG.md
chart/kube-arangodb/templates/deployment.yaml

GT-233 Fix manual overwrite for ReplicasCount in helm

---

pkg/apis/deployment/v1/plan_test.go
pkg/util/times.go

It was returning false even for a.Equals(a) because of wrong check in times.go

Fix equality check for Plan Action

---

README.md

- remove duplicated information
- fix typos
- update information on Upgrade process
- update helm commands to be compatible with latest Helm version

[Maintenance] Simplify and update README file

---

index.yaml

Add missing CRD charts to Helm registry

---

internal/doc_definition_test.go
internal/docs_parser_test.go
internal/docs_test.go
pkg/crd/crds/database-deployment.go

- split huge file
- better names
- extract parsing from generator function
This will be used for CR schema validation generator.

(Refactoring) Extract CR struct fields parser from renderer for re-usage

---

.circleci/config.yml

Now check can be triggered using pipeline parameter

Allow running manifests-verify without changes in files

---

CHANGELOG.md
docs/how-to/debugging.md

Covers: https://github.com/arangodb/kube-arangodb/issues/1786

[Documentation] Remove Interactive args for the DebugPackage command
